swagger: "2.0"
# openapi: "3.0.0"
info:
  description: "Test 12345 You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters."
  version: "1.0.0"
  title: "RPG-Admin Service"
  termsOfService: "https://github.com/user-name/repository-name"
  contact:
    email: "test@example.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:3200"
basePath: "/api/v1"
tags:
- name: "members"
  description: "Administrators infomation"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
- name: "auth"
  description: "Operations about authentication"
  externalDocs:
    description: "Find out more about our store"
    url: "http://swagger.io"
- name: "user"
  description: "Operations about user"
  externalDocs:
    description: "Find out more about our store"
    url: "http://swagger.io"
schemes:
- "https"
- "http"
paths:
  /admin/members:
    get:
      tags:
      - "members"
      summary: "Find members"
      description: "Returns administrators data"
      # operationId: "getPetById"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Member"
        "400":
          description: "Invalid ID supplied"
          schema:
            $ref: "#/definitions/ApiErrorResponse"
        "404":
          description: "Members not found"
          schema:
            $ref: "#/definitions/ApiErrorResponse"
      security:
      - api_key: []
  /admin/members/csv:
    get:
      tags:
      - "members"
      summary: "Find members as CSV data"
      description: "Returns administrators data by csv file"
      # operationId: "getPetById"
      produces:
      - "application/csv"
      parameters: []
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/FileData"
        "400":
          description: "Invalid ID supplied"
          schema:
            $ref: "#/definitions/ApiErrorResponse"
        "404":
          description: "Members not found"
          schema:
            $ref: "#/definitions/ApiErrorResponse"
      security:
      - api_key: []
  /admin/members/member:
    post:
      tags:
      - "members"
      summary: "Create Administrator"
      description: ""
      operationId: "createMemberWithForm"
      consumes:
      - "application/json"
      - "application/x-www-form-urlencoded"
      produces:
      - "application/json"
      parameters:
      - name: "api_key"
        in: "header"
        description: "api key"
        required: false
        type: "string"
      - name: "name"
        in: "formData"
        description: "name of administrator"
        required: true
        type: "string"
      - name: "email"
        in: "formData"
        description: "email of administrator"
        required: true
        type: "string"
      - name: "roleId"
        in: "formData"
        description: "role of administrator"
        required: true
        type: "integer"
      - name: "password"
        in: "formData"
        description: "password of administrator"
        required: true
        type: "string"
      - name: "password_confirmation"
        in: "formData"
        description: "confirm password of administrator"
        required: true
        type: "string"
      responses:
        "405":
          description: "Invalid input"
          schema:
            $ref: "#/definitions/ApiErrorResponse"
        "422":
          description: "Invalid input"
          schema:
            $ref: "#/definitions/ApiErrorResponse"
      security:
      - members_auth:
        - "write:members"
        - "read:members"
  /admin/members/member/{id}:
    patch:
      tags:
      - "members"
      summary: "Updates member data with form data"
      description: ""
      operationId: "updateMemberWithForm"
      consumes:
      - "application/json"
      - "application/x-www-form-urlencoded"
      produces:
      - "application/json"
      parameters:
      - name: "api_key"
        in: "header"
        description: "api key"
        required: false
        type: "string"
      - name: "id"
        in: "path"
        description: "ID of member"
        required: true
        type: "integer"
        format: "int64"
      - name: "name"
        in: "formData"
        description: "name of administrator"
        required: true
        type: "string"
      - name: "email"
        in: "formData"
        description: "email of administrator"
        required: true
        type: "string"
      - name: "roleId"
        in: "formData"
        description: "role of administrator"
        required: true
        type: "integer"
      responses:
        "405":
          description: "Invalid input"
          schema:
            $ref: "#/definitions/ApiErrorResponse"
        "422":
          description: "Invalid input"
          schema:
            $ref: "#/definitions/ApiErrorResponse"
      security:
      - members_auth:
        - "write:members"
        - "read:members"
    delete:
      tags:
      - "members"
      summary: "Deletes a member"
      description: ""
      operationId: "deleteMember"
      produces:
      - "application/json"
      parameters:
      - name: "api_key"
        in: "header"
        description: "api key"
        required: false
        type: "string"
      - name: "id"
        in: "path"
        description: "ID of member"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "400":
          description: "Invalid ID supplied"
          schema:
            $ref: "#/definitions/ApiErrorResponse"
        "422":
          description: "Invalid ID supplied"
          schema:
            $ref: "#/definitions/ApiErrorResponse"
        "404":
          description: "Membeer not found"
          schema:
            $ref: "#/definitions/ApiErrorResponse"
      security:
      - members_auth:
        - "write:members"
        - "read:members"
  /auth/admin/login:
    post:
      tags:
      - "auth"
      summary: "Logs user into the system"
      description: "Login Function"
      consumes:
      - "application/json"
      - "application/x-www-form-urlencoded"
      produces:
      - "application/json"
      parameters:
      - name: "email"
        in: "formData"
        description: "email of administrator"
        required: true
        type: "string"
      - name: "password"
        in: "formData"
        description: "password of administrator"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful Login"
          schema:
            $ref: "#/definitions/Member"
          # headers:
          #  X-Rate-Limit:
          #    type: "integer"
          #    format: "int32"
          #    description: "calls per hour allowed by the user"
        "400":
          description: "Invalid username/password supplied"
          schema:
            $ref: "#/definitions/ApiErrorResponse"
        "422":
          description: "Invalid input"
          schema:
            $ref: "#/definitions/ApiErrorResponse"
  /auth/admin/logout:
    post:
      tags:
      - "auth"
      summary: "Logs out current logged in user session"
      description: "Logout Function"
      consumes:
      - "application/json"
      - "application/x-www-form-urlencoded"
      produces:
      - "application/json"
      parameters:
      - name: "api_key"
        in: "header"
        description: "api key"
        required: false
        type: "string"
      responses:
        "200":
          description: "successful Logout"
          schema:
            $ref: "#/definitions/ApiResponse"
        "401":
          description: "Unahthorithed"
          schema:
            $ref: "#/definitions/ApiErrorResponse"
        default:
          description: "unsuccessful operation"
          schema:
            $ref: "#/definitions/ApiErrorResponse"
  /auth/admin/refresh:
    post:
      tags:
      - "auth"
      summary: "Refresh authenticated token"
      description: "Refresh Authenticated token Function"
      consumes:
      - "application/json"
      - "application/x-www-form-urlencoded"
      produces:
      - "application/json"
      parameters:
      - name: "api_key"
        in: "header"
        description: "api key"
        required: false
        type: "string"
      responses:
        "200":
          description: "Authenticated"
          schema:
            $ref: "#/definitions/AuthenticatedUser"
        "401":
          description: "Unahthorithed"
          schema:
            $ref: "#/definitions/ApiErrorResponse"
        default:
          description: "unsuccessful operation"
          schema:
            $ref: "#/definitions/ApiErrorResponse"
  /auth/admin/self:
    post:
      tags:
      - "auth"
      summary: "Check authenticated"
      description: "Check Authenticated Function"
      consumes:
      - "application/json"
      - "application/x-www-form-urlencoded"
      produces:
      - "application/json"
      parameters:
      - name: "api_key"
        in: "header"
        description: "api key"
        required: false
        type: "string"
      responses:
        "200":
          description: "Authenticated"
          schema:
            $ref: "#/definitions/AuthenticatedUser"
        "401":
          description: "Unahthorithed"
          schema:
            $ref: "#/definitions/ApiErrorResponse"
        default:
          description: "unsuccessful operation"
          schema:
            $ref: "#/definitions/ApiErrorResponse"
  /user:
    post:
      tags:
      - "user"
      summary: "Create user"
      description: "This can only be done by the logged in user."
      operationId: "createUser"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Created user object"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        default:
          description: "successful operation"
  /user/login:
    get:
      tags:
      - "user"
      summary: "Logs user into the system"
      description: ""
      operationId: "loginUser"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "username"
        in: "query"
        description: "The user name for login"
        required: true
        type: "string"
      - name: "password"
        in: "query"
        description: "The password for login in clear text"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "string"
          headers:
            X-Rate-Limit:
              type: "integer"
              format: "int32"
              description: "calls per hour allowed by the user"
            X-Expires-After:
              type: "string"
              format: "date-time"
              description: "date in UTC when token expires"
        "400":
          description: "Invalid username/password supplied"
  /user/logout:
    get:
      tags:
      - "user"
      summary: "Logs out current logged in user session"
      description: ""
      operationId: "logoutUser"
      produces:
      - "application/xml"
      - "application/json"
      parameters: []
      responses:
        default:
          description: "successful operation"
securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  members_auth:
    type: "oauth2"
    authorizationUrl: "http://example.com"
    flow: "implicit"
    scopes:
      write:members: "modify members in your account"
      read:members: "read your members"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      username:
        type: "string"
      firstName:
        type: "string"
      lastName:
        type: "string"
      email:
        type: "string"
      password:
        type: "string"
      phone:
        type: "string"
      userStatus:
        type: "integer"
        format: "int32"
        description: "User Status"
    xml:
      name: "User"
  AuthenticatedUser:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      authority:
        type: "integer"
        format: "int32"
        description: "User authority"
    xml:
      name: "AuthenticatedUser"
  Member:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      email:
        type: "string"
      password:
        type: "string"
      phone:
        type: "string"
      roleId:
        type: "integer"
        format: "int64"
        description: "Admin`s role id"
    xml:
      name: "Member"
  FileData:
    description: "binary data"
    type: "object"
  Tag:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
    xml:
      name: "Tag"
  ApiErrorResponse:
    type: "object"
    properties:
      status:
        type: "integer"
        format: "int32"
      errors:
        type: "array"
        items:
          type: "string"
      message:
        type: "string"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
